services:
  gpk_fwmaker:
    build: .
    image: gpk_fwmaker_0006
    volumes:
      - ~/GPKFW:/root/keyboards
    tty: true
    stdin_open: true
    ports:
      - 3123:3000
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24    