services:
  gpk_fwmaker:
    build: .
    image: gpk_fwmaker_0007
    volumes:
      - ~/GPKFW:/root/keyboards
    tty: true
    stdin_open: true
    ports:
      - 3123:3000
    dns:
      - 8.8.8.8
      - 8.8.4.4
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24    